title: CMSE
description: >-
  The CMSE group at the University of Liverpool uses simulations to study and engineer materials.
theme: minima

# Pages shown in the top navigation bar, in this order
header_pages:
  - research.md
  - people.md
  - contact.md
